### ISSUE TITLE
Add onSelectionChange event

### ISSUE THREAD

**Issue by b3b00** [b3b00/svelte-treeview#6]
Add an onSelectionChange event on TreeView component to get slection when when changed.

The selectionchange event will be thrown by the TreeViewNode component whenever a node (or leaf) selected/unselected modifyin the list of selected nodes.
The onSelectionChanged callback will be passed a list of selected node (that is more or less the selection attribute of the TreeView component)

```html

<script>

let const selectionChanged = selection => {
    //do something clever with the new selection
    // selection is an array of node
    for (let i = 0; i < selection.detail.length; i++) {
        console.log('selected node #'+i, selection.detail[i]);
    }
}

</script>
<treeview selectable root={data} on:selectionChanged={selectionChanged}/>


```

**Comment by reconrez** [comment]
Can you please elaborate the issue?

**Comment by b3b00** [comment]
@reconrez , i've detailed the issue. hope this is now better.
